const languages = {
    en: {
        title: 'Optio-Options Analysis Software',
        featuresTitle: 'Features',
        introText: 'Welcome to our Option Pricing and Monte Carlo Simulation program. This program provides accurate pricing for call and put options and uses Monte Carlo simulation to model the price of underlying assets. With a user-friendly interface and interactive charts, you can easily upload and analyze your data.',
        feature1: 'Accurate Pricing of Call and Put Options',
        feature1Description: 'This program uses the Black-Scholes model to value put and call options. The model provides good accuracy and is time-tested.',
        feature2: 'Monte Carlo Simulation for Price Modeling',
        feature2Description: 'Utilize Monte Carlo simulations to model the future prices of underlying assets, allowing for comprehensive risk and return assessments.',
        feature3: 'User-friendly Interface',
        feature3Description: 'The intuitive and easy-to-navigate interface makes it simple for users of all experience levels to utilize the program\'s powerful features.',
        feature4: 'Interactive Charts',
        feature4Description: 'Interactive charts provide a visual representation of your data, making it easier to identify trends and make informed decisions.',
        feature5: 'Support for CSV Data Upload',
        feature5Description: 'Easily upload your data in CSV format to start analyzing it with our program\'s advanced tools and features.',
        exampleTitle: 'Example Work',
        futurePlansTitle: 'Future Plans',
        futurePlansText: 'We plan to add support for more complex financial instruments, improve the interface, and add automatic model parameter optimization capabilities.',
        tabVolatilityAnalysis: 'Jumping diffusion',
		tabHistoricalData: 'Put option delta',
		tabMonteCarlo: 'Geometric Brownian motion',
		tabOptionPricing: 'Call option price',
		systemRequirementsTitle: 'System Requirements',
        systemRequirements: [
            'Operating System: Windows 10 or higher.',
            'Processor: Intel Core i5 or higher',
            'RAM: 8 GB or higher',
            'Disk Space: 500 MB or more'
        ],
		installTitle: 'Install',
		installText: 'Download the version in the language you need. Unzip the zip archive to a convenient location. In the folder, find the file "main.exe" and run this application, after a short download the main application window will appear.',
        faqTitle: 'FAQ',
        faqQuestion1: 'How to upload data into the program?',
        faqAnswer1: 'You can upload data in CSV format using the corresponding function in the program menu.',
        faqQuestion2: 'What data is needed for option pricing?',
        faqAnswer2: 'For option pricing, you need historical data on the underlying asset prices, volatility, risk-free rate, and time to option expiration.',
        faqQuestion3: 'How does the Monte Carlo method work?',
        faqAnswer3: 'The Monte Carlo method uses random sampling to simulate future prices of the underlying asset, allowing for risk and return assessment of financial instruments.',
		faqQuestion4: 'Does this program have instructions?',
		faqAnswer4: 'Yes, to obtain more detailed information about the program, you need to open the "Reference" tab in the program. This tab describes some features of the program.',
        screenshots:  {
            optionPricing: 'assets/callopt-en.png',
            monteCarlo: 'assets/MK-en.png',
            historicalData: 'assets/put-delta-en.png',
            volatilityAnalysis: 'assets/jd-en.png'
        }
    },
    ru: {
        title: 'Программа Анализа Опционов-Optio',
        featuresTitle: 'Особенности',
        introText: 'Добро пожаловать в нашу программу оценки опционов и моделирования Монте-Карло. Эта программа предоставляет точную оценку опционов колл и пут и использует моделирование Монте-Карло для моделирования цены базовых активов. С удобным интерфейсом и интерактивными графиками вы можете легко загружать и анализировать свои данные.',
        feature1: 'Точная оценка опционов колл и пут',
        feature1Description: 'Данная программа использует модель Блэка-Шоулза для оценки опционов пут и колл. Модель обеспечивает хорошую точность и проверена временем.',
        feature2: 'Моделирование цен методом Монте-Карло',
        feature2Description: 'Используйте моделирование Монте-Карло для прогнозирования будущих цен базовых активов, что позволяет проводить всестороннюю оценку рисков и доходности.',
        feature3: 'Удобный интерфейс',
        feature3Description: 'Интуитивно понятный и простой в использовании интерфейс позволяет пользователям любого уровня легко пользоваться мощными функциями программы.',
        feature4: 'Интерактивные графики',
        feature4Description: 'Интерактивные графики предоставляют визуальное представление ваших данных, что облегчает выявление трендов и принятие обоснованных решений.',
        feature5: 'Поддержка загрузки данных в формате CSV',
        feature5Description: 'Легко загружайте данные в формате CSV, чтобы начать анализировать их с помощью продвинутых инструментов и функций нашей программы.',
        exampleTitle: 'Примеры работы',
        futurePlansTitle: 'Будущие планы',
        futurePlansText: 'Мы планируем добавить поддержку более сложных финансовых инструментов, улучшить интерфейс и добавить возможность автоматической оптимизации параметров моделей.',
        systemRequirementsTitle: 'Системные требования',
		tabVolatilityAnalysis: 'Прыжковая диффузия',
		tabHistoricalData: 'Дельта пут опциона',
		tabMonteCarlo: 'Геометрическое броуновское движение',
		tabOptionPricing: 'Цена колл опциона',
        systemRequirements: [
            'Операционная система: Windows 10 или выше.',
            'Процессор: Intel Core i5 или выше',
            'Оперативная память: 8 ГБ или выше',
            'Место на диске: 500 МБ или больше'
        ],
		installTitle: 'Установка',
		installText: 'Скачайте версию на нужном вам языке. Распакуйте zip-архив в удобное место. В папке найдите файл "main.ехе" и запустите данное приложение, после небольшой загрузки появиться главное окно приложения.',
        faqTitle: 'FAQ',
        faqQuestion1: 'Как загрузить данные в программу?',
        faqAnswer1: 'Вы можете загрузить данные в формате CSV, используя соответствующую функцию в меню программы.',
        faqQuestion2: 'Какие данные нужны для оценки опционов?',
        faqAnswer2: 'Для оценки опционов вам понадобятся исторические данные о ценах базового актива, волатильность, ставка безрискового процента и срок до экспирации опциона.',
        faqQuestion3: 'Как работает метод Монте-Карло?',
        faqAnswer3: 'Метод Монте-Карло использует случайные выборки для моделирования будущих цен базового актива, что позволяет оценить риск и доходность финансовых инструментов.',
		faqQuestion4: 'Есть ли у этой программы инструкция?',
		faqAnswer4: 'Да, для получения более детальной информации работе программы необходимо открыть вкладку "Справка" в программе. В этой вкладке описаны некоторые особенности работы программы.',
        screenshots: {
            optionPricing: 'assets/callopt.png',
            monteCarlo: 'assets/MK.png',
            historicalData: 'assets/put-delta-ru.png',
            volatilityAnalysis: 'assets/jd-ru.png'
        }
    }
};
